/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'overallauth',
    path: '/overallauth',
    component: 'layout.base',
    meta: {
      title: 'overallauth',
      i18nKey: 'route.overallauth',
      icon: 'carbon:cloud-service-management',
      order: 99
    },
    children: [
      {
        name: 'overallauth_role',
        path: '/overallauth/role',
        component: 'view.overallauth_role',
        meta: {
          title: 'overallauth_role',
          i18nKey: 'route.overallauth_role',
          icon: 'carbon:user-role',
          order: 2,
          permissions: ['AbpIdentity.Roles']
        }
      },
      {
        name: 'overallauth_user',
        path: '/overallauth/user',
        component: 'view.overallauth_user',
        meta: {
          title: 'overallauth_user',
          i18nKey: 'route.overallauth_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          permissions: ['AbpIdentity.Users']
        }
      }
    ]
  }
];
